modLoader="javafml"
loaderVersion="[33,)"
license="All Rights Reserved"

[[mods]]
  modId="zombiesmod"
  version="${version}"
  displayName="Zombies Mod"
  authors="thamid"

[[dependencies.zombiesmod]]
  modId="forge"
  mandatory=true
  versionRange="[33,)"
  ordering="NONE"
  side="CLIENT"

[[dependencies.zombiesmod]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.2,)"
  ordering="NONE"
  side="CLIENT"